# Generated by Django 5.0.7 on 2024-08-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bizningmahsulot_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
                ('sarlavha', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismfamilya', models.CharField(max_length=200)),
                ('pochta', models.EmailField(blank=True, max_length=254, null=True)),
                ('telfon', models.CharField(max_length=20)),
                ('murojaat_sababi', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismfamilya', models.CharField(max_length=200)),
                ('kasbi', models.CharField(max_length=200)),
                ('rasmi', models.ImageField(upload_to='media/')),
                ('instagram', models.CharField(max_length=300)),
                ('facebook', models.CharField(max_length=300)),
                ('youtube', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
