# Generated by Django 5.0.7 on 2024-08-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutawards_contactform_xodimlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutawards',
            name='sarlavha_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutawards',
            name='sarlavha_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutawards',
            name='sarlavha_uz',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutawards',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutawards',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutawards',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bizningmahsulot',
            name='date_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bizningmahsulot',
            name='date_ru',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bizningmahsulot',
            name='date_uz',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bizningmahsulot',
            name='nomi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bizningmahsulot',
            name='nomi_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bizningmahsulot',
            name='nomi_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
