# Generated by Django 5.0.7 on 2024-08-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutawards_sarlavha_en_aboutawards_sarlavha_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutawards',
            name='sarlavha1',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutawards',
            name='sarlavha1_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutawards',
            name='sarlavha1_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutawards',
            name='sarlavha1_uz',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
