# Generated by Django 5.0.7 on 2024-08-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutawards_sarlavha1_aboutawards_sarlavha1_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('text_uz', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
            ],
        ),
    ]
