# Generated by Django 5.0.7 on 2024-08-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutname',
            name='text',
        ),
        migrations.RemoveField(
            model_name='aboutname',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='aboutname',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='aboutname',
            name='text_uz',
        ),
        migrations.AddField(
            model_name='aboutname',
            name='li1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutname',
            name='li1_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutname',
            name='li1_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutname',
            name='li1_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutname',
            name='li2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutname',
            name='li2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutname',
            name='li2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutname',
            name='li2_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutname',
            name='li3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutname',
            name='li3_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutname',
            name='li3_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutname',
            name='li3_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
