# Generated by Django 5.0.7 on 2024-08-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_aboutname_text_remove_aboutname_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodimlar',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='instagram',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='rasmi',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='youtube',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
