# Generated by Django 5.0.7 on 2024-08-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_xodimlar_facebook_alter_xodimlar_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulotlar',
            name='sarlavha_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='mahsulotlar',
            name='sarlavha_ru',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='mahsulotlar',
            name='sarlavha_uz',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='mahsulotlar',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mahsulotlar',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mahsulotlar',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='ismfamilya_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='ismfamilya_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='ismfamilya_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='kasbi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='kasbi_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='kasbi_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
