# Generated by Django 5.0.7 on 2024-08-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_mahsulotlar_sarlavha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutawards',
            name='rasm1',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
