# Generated by Django 5.0.7 on 2024-08-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aboutawards_rasm1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=200)),
                ('addres_uz', models.CharField(max_length=200, null=True)),
                ('addres_en', models.CharField(max_length=200, null=True)),
                ('addres_ru', models.CharField(max_length=200, null=True)),
                ('pochta', models.EmailField(max_length=254)),
                ('pochta_uz', models.EmailField(max_length=254, null=True)),
                ('pochta_en', models.EmailField(max_length=254, null=True)),
                ('pochta_ru', models.EmailField(max_length=254, null=True)),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField()),
            ],
        ),
    ]
