# Generated by Django 5.0.7 on 2024-08-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone1',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone2',
            field=models.CharField(max_length=13),
        ),
    ]
