# Generated by Django 5.0.7 on 2024-08-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_info_phone1_alter_info_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone1',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone2',
            field=models.CharField(max_length=16),
        ),
    ]
